apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
spec:
  template:
    spec:
      containers:
      - name: subscriptions
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"